blueprint:
  name: Motion-activated Light with fixed brightness
  description: Turn on a light when motion is detected with fixed brightness.
  domain: automation
  source_url: https://github.com/pieterhelli/ha/edit/main/motion_light_fixedbrightness.yaml
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    brightness:
      name: Brightness
      description: Desired brightness when light is turned on by motion
      default: 100
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider
          unit_of_measurement: percent

# If motion is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"

action:
  - alias: "Turn on the light"
    service: light.turn_on
    data:
      brightness_pct: !input brightness
    target: !input light_target
  - alias: "Wait until there is no motion from device"
    wait_for_trigger:
      platform: state
      entity_id: !input motion_entity
      from: "on"
      to: "off"
  - alias: "Wait the number of seconds that has been set"
    delay: !input no_motion_wait
  - alias: "Turn off the light"
    service: light.turn_off
    target: !input light_target
